import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

function loadDotEnv() {
  const envPath = path.join(root, '.env');
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!process.env[key]) process.env[key] = val;
  }
}

loadDotEnv();

const url = process.env.SUPABASE_URL?.trim() || 'https://rnuqzkjeuthbgbjcfywx.supabase.co';
const anonKey = process.env.SUPABASE_ANON_KEY?.trim() || '';

if (!anonKey) {
  console.warn('Warning: SUPABASE_ANON_KEY is empty. Set it in .env or Vercel Environment Variables.');
}

const out = `// Generated by scripts/build-config.mjs — do not edit by hand
window.FLOW_SUPABASE_CONFIG = {
  url: ${JSON.stringify(url)},
  anonKey: ${JSON.stringify(anonKey)},
};
`;

const outPath = path.join(root, 'supabase', 'config.js');
fs.writeFileSync(outPath, out);
console.log('Wrote supabase/config.js');
